title: Spatial Analysis for Energy
author: Ayrton Bourn, Santiago De La Fuente, Camilo Perico, Clem Attwood, Joanna Kuleszo, Dylan Johnson, Harry Wadley
logo: 'img/logo.svg'

execute:
  execute_notebooks: 'off'

repository:
  url: https://github.com/ESDA-Spatial/ESDA-Spatial
  
html:
  use_issues_button: true
      
sphinx:
  config:
    timeout: 300
    myst_amsmath_enable: true
  extra_extensions:
    - "sphinx_thebe"

launch_buttons:
  thebe: true