name: ESDA-Spatial

channels:
    - r
    - conda-forge

dependencies:
    - jupyterlab
    - nbclient
    - r-base
    - r-essentials
    - r-sf
    - r-raster
    - r-spatstat
    - r-geojsonio
    - r-leaflet
    - r-gsubfn
    - r-zeallot
    - r-tmap
    - r-rgdal
    - r-kernsmooth
    
    - pip:
        - sphinx-thebe
