title: Spatial Analysis for Energy
author: Ayrton Bourn, Santiago De La Fuente, Clem Attwood, Joanna Kuleszo, Camilo Perico
logo: 'img/logo.svg'

execute:
  execute_notebooks: on 

repository:
  url: https://github.com/AyrtonB/ESDA-Spatial
      
sphinx:
  config:
    timeout: 300
    myst_amsmath_enable: true
  extra_extensions:
    - "sphinx_thebe"

launch_buttons:
  thebe: true