title: Spatial Analysis for Energy
author: Ayrton Bourn, Santiago De La Fuente, Clem Attwood, Joanna Kuleszo, Camilo Perico
logo: 'img/logo.svg'


repository:
  url: https://github.com/AyrtonB/ESDA-Spatial

html:
  use_repository_button: true
  use_edit_page_button: true
  comments:
    utterances:
      repo: 'https://github.com/AyrtonB/ESDA-Spatial'
      
sphinx:
  config:
    timeout: 300