name: ESDA-Spatial

channels:
    - r
    - conda-forge

dependencies:
    - jupyterlab
    - r-essentials
    - r-sf
    - r-raster
    - r-spatstat
    - r-geojsonio
    - r-leaflet
    - r-gsubfn
    - r-zeallot
    - r-tmap
    - r-rgdal